### ISSUE TITLE
Draw Announcements over the content

### ISSUE THREAD

**Issue by sampathbalivada** [ManasMalla/devfest-vizag-2024#16]
The announcement bar is behind the website content move it to the top.

![image](https://github.com/user-attachments/assets/efbc9b34-3710-4c69-8683-d0ae3a1bfbec)

**Comment by ManasMalla** [comment]
**Solved** with PR #17 

![image](https://github.com/user-attachments/assets/c084df84-d7b5-4996-b5c6-6a510ff59cce)
