### ISSUE TITLE
Add update function to `update-profile` in `profile` route

### ISSUE THREAD

**Issue by ManasMalla** [ManasMalla/devfest-vizag-2024#52]
When clicking on update profile the `profile` doesn't update the Firebase credentials.

**Comment by ManasMalla** [comment]
@ChandanKhamitkar man can you work on the issues of the user document not updating when the user is new onto the platform and make socials as an empty array if undefined when updating profile?

**Comment by ChandanKhamitkar** [comment]
Yeah Sure @ManasMalla
